In [8]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import scipy

In [4]:
# Definir la matriz A
A = np.array([[1, 1, 4],
              [0, -1, 3]])

# Calcular el rango de A
rank_A = np.linalg.matrix_rank(A)
print(rank_A)

# Número de filas y columnas
rows_A, cols_A = A.shape

# Verificar si tiene inversa por la izquierda y por la derecha
inverse_left_A = rank_A == cols_A  # Si el rango es igual al número de columnas
inverse_right_A = rank_A == rows_A  # Si el rango es igual al número de filas

# Mostrar resultados
rank_A, inverse_left_A, inverse_right_A
 
print("La matriz A tiene inversa por la izquierda: ", inverse_left_A)
print("La matriz A tiene inversa por la derecha: ", inverse_right_A)



2
La matriz A tiene inversa por la izquierda:  False
La matriz A tiene inversa por la derecha:  True


In [5]:
# Pseudoinversa de A
# Definir las matrices A, B y C
A = np.array([[1, 1],
              [1, -1],
              [1, 1]])

B = np.array([[0, 1, 0],
              [1, 0, 1]])

C = np.array([[0, 1, -2, 1],
              [1, 0, 1, 0],
              [0, 0, 1, -1]])

# Calcular la pseudoinversa de Moore-Penrose de cada matriz
A_pinv = np.linalg.pinv(A)
B_pinv = np.linalg.pinv(B)
C_pinv = np.linalg.pinv(C)

# Mostrar los resultados
A_pinv, B_pinv, C_pinv


(array([[ 0.25,  0.5 ,  0.25],
        [ 0.25, -0.5 ,  0.25]]),
 array([[0. , 0.5],
        [1. , 0. ],
        [0. , 0.5]]),
 array([[ 2.50000000e-01,  7.50000000e-01, -6.30743584e-16],
        [ 7.50000000e-01,  2.50000000e-01,  1.00000000e+00],
        [-2.50000000e-01,  2.50000000e-01,  9.09255562e-17],
        [-2.50000000e-01,  2.50000000e-01, -1.00000000e+00]]))

In [12]:
# Factorizacion LU de una matriz
# Definir la matriz A
A = np.array([[1, 2, 3],
              [2, 8, 11],
              [3, 22, 33]]) # Matriz de 3x3

# Calcular la factorización LU
P, L, U = scipy.linalg.lu(A)

# Mostrar los resultados
P, L, U

(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.66666667, 1.        , 0.        ],
        [0.33333333, 0.8       , 1.        ]]),
 array([[  3.        ,  22.        ,  33.        ],
        [  0.        ,  -6.66666667, -11.        ],
        [  0.        ,   0.        ,   0.8       ]]))

In [11]:
# Definir la matriz A y el vector b
A = np.array([[-1, 1, 5],
              [0, 2, 8],
              [-4, 6, 27]])

b = np.array([2, -8, 25])

# Calcular la pseudoinversa de A (Moore-Penrose)
A_pinv = np.linalg.pinv(A)

# Calcular la solución particular x = A^+ b
x_solution = A_pinv @ b

# Mostrar la pseudoinversa de A y la solución del sistema
A_pinv, x_solution


(array([[  3. ,   1.5,  -1. ],
        [-16. ,  -3.5,   4. ],
        [  4. ,   1. ,  -1. ]]),
 array([-31.,  96., -25.]))